# Generated by Django 2.1.8 on 2019-05-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='pagetitle',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='background_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image'
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image'
            ),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='background_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image'
            ),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='background_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.Image'
            ),
        ),
    ]
